server.port=8080

# Configuración de PostgreSQL configurable mediante Variables de Entorno
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://tokaido.proxy.rlwy.net:32605/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:MZqIvoNRzWKGaCEDxExEQpIDLOVhWKgF}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jackson.property-naming-strategy=SNAKE_CASE
